api_platform:
    title: Darkwaar API
    version: 1.0.0
    mapping:
        paths:
            - '%kernel.project_dir%/config/api_platform'
            - '%kernel.project_dir%/src/Entity'
            - '%kernel.project_dir%/src/ApiResource'
    patch_formats:
        json: ['application/merge-patch+json']
    swagger:
        versions: [3]
        api_keys:
            apiKey:
                name: Authorization
                type: header

    # Enable OpenAPI documentation
    openapi:
        contact:
            name: Darkwaar API Team
            url: https://darkwaar.io
            email: contact@darkwaar.io
        termsOfService: https://darkwaar.io/terms
        license:
            name: MIT
            url: https://opensource.org/licenses/MIT

    # Configure documentation modifiers
#    documentation:
#        accept_language_header:
#            enabled: true
#            header_name: Accept-Language
