framework:
    translator: { fallbacks: ["%locale%"] }
    secret: '%env(APP_SECRET)%'
    form:
        enabled: true
    csrf_protection: true
    http_method_override: true
    session:
        handler_id: ~
#    http_method_override: false
#    handle_all_throwables: true
#    session:
#        handler_id: null
#        cookie_secure: auto
#        cookie_samesite: lax
#        storage_factory_id: session.storage.factory.native
    serializer:
        mapping:
            paths: [ '%kernel.project_dir%/config/serialization' ]
    php_errors:
        log: true
#    router:
#        utf8: true
#        default_uri: '%env(APP_URL)%'
#    cache:
#        app: cache.adapter.filesystem
#        system: cache.adapter.system
#        directory: '%kernel.cache_dir%/pools'
#        default_doctrine_dbal_provider: 'doctrine.system_cache_pool'
#        default_psr6_provider: 'doctrine.system_cache_pool'
#        default_redis_provider: 'redis://localhost'
#        default_memcached_provider: 'memcached://localhost'

when@dev:
    framework:
        profiler: { only_exceptions: false }

when@test: &framework_test
    framework:
        test: true
        session:
            storage_factory_id: session.storage.factory.mock_file

when@test_cached: *framework_test
